import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import './overrides.css';

const commons='https://commons.wikimedia.org/wiki/Special:FilePath/';
const images={
 hero:commons+'Jaffa, Palestine, 1937.jpg?width=1600', doc:commons+'White_Paper_of_1939.jpg?width=1000',
 map:commons+'Palestine_Mandate_1924.jpg?width=1200', churchill:commons+'Winston_Churchill_1941_photo_by_Yousuf_Karsh.jpg?width=700',
 weizmann:commons+'Chaim_Weizmann_1949.jpg?width=700', chamberlain:commons+'Neville_Chamberlain.jpg?width=700',
 jaffa:commons+'Jaffa,_Palestine,_1930s.jpg?width=900', jerusalem:commons+'Jerusalem_1931.jpg?width=900'
};
const events=[
 ['1917','Declaración Balfour','El Gobierno británico expresó su apoyo a un “hogar nacional para el pueblo judío” en Palestina, sin perjuicio de los derechos de las comunidades no judías.'],
 ['1920','Mandato británico','La Sociedad de Naciones confió a Gran Bretaña la administración de Palestina; el Mandato entró en vigor en 1922.'],
 ['1921','Disturbios de Jaffa','La violencia intercomunal y política reveló las tensiones creadas por el nuevo marco mandatado.'],
 ['1922','Libro Blanco de Churchill','Definió el alcance británico del Hogar Nacional Judío y vinculó la inmigración a la capacidad económica de absorción.'],
 ['1929','Disturbios de Palestina','Enfrentamientos en torno al Muro Occidental y otros lugares impulsaron investigaciones sobre tierras, trabajo e inmigración.'],
 ['1930','Libro Blanco de Passfield','Subrayó las obligaciones británicas hacia ambas comunidades y planteó una mayor cautela en tierras e inmigración.'],
 ['1936–1939','Revuelta árabe','Una insurrección palestina árabe contra el Mandato, la inmigración y la adquisición de tierras transformó el contexto político.'],
 ['1937','Comisión Peel','Propuso la partición como solución; sus debates influyeron en los cambios de política posteriores.'],
 ['1939','Libro Blanco','Limitó la inmigración judía y propuso una Palestina independiente en diez años.']
];
const compare={
 'Inmigración':[['1922','Admitida según la capacidad económica de absorción del país.'],['1930','Mayor preocupación por empleo, tierras y desplazamiento; debate sobre controles.'],['1939','75.000 admisiones en cinco años; después, sujeta al consentimiento árabe.']],
 'Tierras':[['1922','No estableció un régimen general de zonas restrictivas.'],['1930','Advirtió sobre el efecto de las compras en los cultivadores árabes y pidió cautela.'],['1939','La normativa posterior delimitó áreas con restricciones o prohibiciones de venta.']],
 'Hogar Nacional':[['1922','Reafirmado, pero Palestina no debía convertirse íntegramente en un Estado judío.'],['1930','Se insistió en equilibrar esta obligación con la protección de la población árabe.'],['1939','Interpretó que el objetivo no era crear un Estado judío; propuso un Estado binacional.']],
 'Futuro político':[['1922','Sin calendario para la independencia; administración bajo Mandato.'],['1930','Propuso un Consejo Legislativo, sin consenso político suficiente.'],['1939','Independencia de Palestina prevista en un plazo de diez años.']]
};
const documents=[
 ['British Policy in Palestine','1922','Colonial Office','El Libro Blanco asociado a Winston Churchill.', 'Aclaró la interpretación británica de la Declaración Balfour y del Mandato.', 'White Paper of 1922'],
 ['Palestine Statement of Policy','1930','Colonial Office','Conocido como Libro Blanco de Passfield.', 'Llevó al primer plano las tierras, el trabajo y la igualdad de obligaciones del Mandato.', 'Passfield White Paper'],
 ['Palestine: Statement of Policy','1939','Gobierno de Su Majestad','El tercer Libro Blanco, publicado en mayo de 1939.', 'Supuso un giro decisivo sobre inmigración y horizonte constitucional.', 'White Paper of 1939'],
 ['Declaración Balfour','1917','Foreign Office','Carta de Arthur Balfour a Lord Rothschild.', 'Texto de referencia para los debates posteriores sobre el Hogar Nacional.', 'Balfour Declaration'],
 ['Mandato para Palestina','1922','Sociedad de Naciones','Instrumento jurídico internacional del Mandato.', 'Estableció las responsabilidades de la administración británica.', 'British Mandate for Palestine'],
 ['Comisión Peel','1937','Palestine Royal Commission','Informe de investigación y propuesta de partición.', 'Reordenó el debate constitucional antes de 1939.', 'Peel Commission']
];
const people=[
 ['Winston Churchill','1874–1965','Secretario de Estado para las Colonias','En 1922 avaló una formulación que reafirmaba el Hogar Nacional Judío, a la vez que delimitaba su alcance político.',images.churchill],
 ['Lord Passfield / Sidney Webb','1859–1947','Secretario de Estado para las Colonias','Su Libro Blanco de 1930 reflejó una preocupación más acusada por los efectos sociales de la política del Mandato.',null],
 ['Neville Chamberlain','1869–1940','Primer ministro británico','Su gobierno publicó el Libro Blanco de 1939 en el contexto de la revuelta árabe y la inminencia de la guerra.',images.chamberlain],
 ['Chaim Weizmann','1874–1952','Dirigente sionista','Presidente de la Organización Sionista Mundial; fue una voz central en las negociaciones sobre política británica.',images.weizmann],
 ['Musa Kazim al-Husseini','1853–1934','Dirigente palestino árabe','Figura destacada del movimiento político palestino durante el Mandato y crítico de sus políticas.',null]
];
function Reveal({children,className=''}){return <div className={'reveal '+className}>{children}</div>}
function App(){
 const [menu,setMenu]=useState(false),[event,setEvent]=useState(3),[topic,setTopic]=useState('Inmigración'),[doc,setDoc]=useState(null),[place,setPlace]=useState('Jerusalén'),[open,setOpen]=useState(null);
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>o.observe(x));return()=>o.disconnect()},[]);
 const links=['Inicio','Contexto','1922','1930','1939','Comparar','Documentos','Fuentes'];
 const places={'Jerusalén':'Centro administrativo y religioso; fue escenario de disputas políticas y de movilización durante el Mandato.','Jaffa':'Puerto histórico y lugar de los disturbios de 1921; su economía y demografía estuvieron estrechamente vinculadas a los debates migratorios.','Tel Aviv':'Ciudad judía en rápida expansión junto a Jaffa, símbolo de los cambios urbanos del período.','Haifa':'Puerto y centro industrial estratégico, conectado a las infraestructuras imperiales británicas.','Hebrón':'La violencia de 1929 marcó profundamente la historia local y las relaciones entre comunidades.','Acre':'Ciudad portuaria histórica del norte, vinculada a las rutas comerciales de la Palestina mandataria.'};
 return <><header><a className="brand" href="#inicio">LB <i>1922—39</i></a><nav className={menu?'open':''}>{links.map(x=><a onClick={()=>setMenu(false)} href={'#'+x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}>{x}</a>)}</nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menú"><span/><span/></button></header>
 <main>
 <section id="inicio" className="hero"><div className="hero-image" style={{backgroundImage:`url("${images.hero}")`}}/><div className="hero-copy"><p className="eyebrow">Exposición digital · Palestina bajo el Mandato</p><h1>Los<br/><em>Libros Blancos</em></h1><h2>La evolución de la política británica en Palestina, 1922–1939</h2><p>Entre 1922 y 1939, el gobierno británico modificó progresivamente su política respecto de Palestina bajo el Mandato. Los Libros Blancos permiten observar esta transformación y las tensiones entre las obligaciones británicas, el proyecto sionista y las demandas de la población árabe.</p><a href="#contexto" className="line-button">Explorar la historia <b>↓</b></a></div><p className="credit">Palestina bajo el Mandato · Imagen de archivo vía Wikimedia Commons</p></section>
 <section id="contexto" className="section context"><Reveal><p className="eyebrow">01 / Antes de los Libros Blancos</p><h2>El contexto</h2><p className="lede">El Mandato británico fue un marco internacional y, a la vez, un campo de conflicto político. La cronología no explica por sí sola el período: orienta una lectura de las decisiones, las resistencias y sus consecuencias.</p></Reveal><div className="timeline">{events.map((e,i)=><button className={event===i?'active':''} onClick={()=>setEvent(i)}><span>{e[0]}</span><i/></button>)}</div><div className="event-detail"><span className="event-no">{String(event+1).padStart(2,'0')}</span><div><h3>{events[event][1]}</h3><p>{events[event][2]}</p></div><div className="event-mark">{events[event][0]}</div></div></section>
 <Paper id="1922" year="1922" title="Libro Blanco de Churchill" official="British Policy in Palestine" accent="El compromiso, delimitado" image={images.jaffa} panels={[['El Hogar Nacional Judío','Reafirmó el compromiso con el establecimiento de un Hogar Nacional Judío. A la vez, sostuvo que no significaba convertir a Palestina en su totalidad en un Estado judío.'],['Inmigración','La admisión de inmigrantes judíos debía depender de la capacidad económica del país para absorberlos.'],['Población árabe','El gobierno declaró que los derechos civiles y religiosos de las comunidades no judías debían ser protegidos.'],['Consecuencias','La fórmula fue recibida de modos distintos: organizaciones sionistas vieron una reafirmación; dirigentes árabes cuestionaron el marco político del Mandato.']]} quote="No se contempla que Palestina en su conjunto deba convertirse en un Hogar Nacional Judío." original="It is not part of the policy ... that Palestine should become as Jewish as England is English." open={open} setOpen={setOpen}/>
 <section id="1930" className="section passfield"><Reveal><p className="eyebrow">03 / Después de 1929</p><div className="two-col"><div><span className="year">1930</span><h2>Libro Blanco<br/><em>de Passfield</em></h2></div><p className="lede">Tras los disturbios de 1929 y las investigaciones británicas, el documento de 1930 llevó las cuestiones de tierras, empleo e inmigración al centro de la política mandataria.</p></div></Reveal><div className="shift"><span>1922</span><div className="arrow">→</div><span>1930</span><p>De la afirmación y el límite económico a una política más atenta a los efectos sociales y territoriales.</p></div><Accordion items={[['Inmigración','El gobierno expresó una preocupación mayor por el desempleo y por las consecuencias de la inmigración en la población árabe.'],['Tierras','Las investigaciones vinculadas al informe alertaron sobre el riesgo de que cultivadores árabes quedaran sin tierra.'],['El Hogar Nacional Judío','Se destacó que las obligaciones del Mandato con las poblaciones judía y árabe debían considerarse conjuntamente.'],['Autogobierno','El documento propuso un Consejo Legislativo; la oposición política impidió que se materializara.'],['Reacción','Las organizaciones sionistas rechazaron enérgicamente el documento. La controversia derivó en una aclaración política posterior, conocida como la carta MacDonald.']]} open={open} setOpen={setOpen}/></section>
 <section id="1939" className="section paper1939"><div className="paper-bg" style={{backgroundImage:`url("${images.doc}")`}}/><Reveal><p className="eyebrow">04 / Un giro decisivo</p><span className="year">1939</span><h2>El límite<br/><em>y el horizonte</em></h2><p className="lede">El Libro Blanco de mayo de 1939 reformuló el rumbo británico en medio de la revuelta árabe y del inminente conflicto europeo.</p></Reveal><div className="triple"><article><span>01</span><h3>Inmigración</h3><strong>75.000</strong><p>inmigrantes judíos en cinco años. Las admisiones posteriores requerirían consentimiento árabe.</p></article><article><span>02</span><h3>Tierras</h3><p>Se anunciaron restricciones a las transferencias de tierras; la reglamentación posterior dividió el territorio en zonas.</p></article><article><span>03</span><h3>Futuro político</h3><p>Una Palestina independiente en diez años, con participación de las poblaciones árabe y judía.</p><div className="decade">1939 <i/> 1949</div></article></div></section>
 <section id="comparar" className="section compare"><Reveal><p className="eyebrow">05 / Lectura transversal</p><h2>Tres Libros Blancos,<br/><em>una política en transformación</em></h2></Reveal><div className="topic-tabs">{Object.keys(compare).map(x=><button onClick={()=>setTopic(x)} className={topic===x?'active':''}>{x}</button>)}</div><div className="comparison">{compare[topic].map((x,i)=><article className={'c'+i}><span>{x[0]}</span><h3>{i===0?'Compromiso':i===1?'Tensión':'Cambio'}</h3><p>{x[1]}</p></article>)}</div></section>
 <section id="documentos" className="section archive"><Reveal><p className="eyebrow">06 / Archivo consultable</p><h2>Documentos</h2><p className="lede">Una selección de textos que estructuraron el debate político. Abra cada pieza para conocer su contexto y relevancia.</p></Reveal><div className="documents">{documents.map((d,i)=><button onClick={()=>setDoc(d)} className="document"><div className={'paper p'+i}><small>{d[1]}</small><b>{d[0]}</b><i>Documento de archivo</i></div><span>{d[0]} <em>{d[1]}</em></span></button>)}</div></section>
 <section id="personas" className="section people"><p className="eyebrow">07 / Voces y decisiones</p><h2>Actores clave</h2>{people.map((p,i)=><Reveal className="person"><div className="portrait">{p[4]?<img src={p[4]} alt={'Retrato de '+p[0]}/>:<span>{p[0].split(' ').map(x=>x[0]).join('').slice(0,2)}</span>}</div><div><span>{p[1]} · {p[2]}</span><h3>{p[0]}</h3></div><p>{p[3]}</p></Reveal>)}</section>
 <section id="mapa" className="section map-section"><Reveal><p className="eyebrow">08 / Geografías del Mandato</p><h2>Palestina bajo el Mandato</h2></Reveal><div className="map-wrap"><img src={images.map} alt="Mapa histórico de Palestina bajo el Mandato"/><div className="pins">{['Jerusalén','Jaffa','Tel Aviv','Haifa','Hebrón','Acre'].map((p,i)=><button className={'pin pin'+i+' '+(place===p?'selected':'')} onClick={()=>setPlace(p)}>{p}</button>)}</div></div><div className="place-info"><span>Ubicación /</span><h3>{place}</h3><p>{places[place]}</p></div></section>
 <section id="glosario" className="section glossary"><p className="eyebrow">09 / Términos para la lectura</p><h2>Glosario</h2><Accordion items={[["Declaración Balfour",'Declaración británica de 1917 relativa al establecimiento en Palestina de un hogar nacional para el pueblo judío.'],['Mandato británico','Administración de Palestina encomendada a Gran Bretaña por la Sociedad de Naciones.'],['Hogar Nacional Judío','Expresión de la Declaración Balfour y del Mandato; su alcance político fue objeto de interpretaciones enfrentadas.'],['Sionismo','Movimiento nacional judío de diversas corrientes que buscó establecer un hogar nacional en Palestina.'],['Inmigración judía','Llegada de población judía a Palestina, central en la política británica y en las disputas del período.'],['Comisión Peel','Comisión Real Británica de 1936–1937 que propuso, entre otras alternativas, la partición.'],['Revuelta árabe de 1936–1939','Levantamiento palestino árabe contra el Mandato británico y la política de inmigración y tierras.'],['Libro Blanco','Documento oficial británico que exponía una orientación de política.'],['Autogobierno','Participación de la población local en las instituciones de gobierno.'],['Capacidad económica de absorción','Criterio de 1922 que vinculaba inmigración y condiciones económicas del territorio.']]} open={open} setOpen={setOpen}/></section>
 <section id="fuentes" className="section sources"><p className="eyebrow">10 / Para seguir investigando</p><h2>Fuentes</h2><div><article><h3>Fuentes primarias</h3><a href="https://avalon.law.yale.edu/20th_century/brwh1922.asp" target="_blank">British Policy in Palestine (1922) · Yale Avalon Project</a><a href="https://avalon.law.yale.edu/20th_century/brwh1939.asp" target="_blank">Palestine: Statement of Policy (1939) · Yale Avalon Project</a><a href="https://www.un.org/unispal/document/auto-insert-201057/" target="_blank">Mandate for Palestine · Naciones Unidas</a></article><article><h3>Fuentes secundarias</h3><a href="https://www.britannica.com/place/Palestine/The-British-mandate" target="_blank">Encyclopaedia Britannica · The British mandate</a><a href="https://www.encyclopedia.com/history/modern-europe/british-and-irish-history/white-paper-1939" target="_blank">White Paper of 1939 · Encyclopedia.com</a><p>Las imágenes enlazadas proceden de Wikimedia Commons; consulte cada archivo para autoría y licencia.</p></article></div></section>
 </main>{doc&&<div className="modal" onClick={()=>setDoc(null)}><article onClick={e=>e.stopPropagation()}><button onClick={()=>setDoc(null)}>×</button><div className="modal-paper"><small>{doc[1]}</small><h2>{doc[0]}</h2><i>{doc[2]}</i></div><p className="eyebrow">Descripción</p><p>{doc[3]}</p><p className="eyebrow">Importancia histórica</p><p>{doc[4]}</p><a target="_blank" href={'https://commons.wikimedia.org/w/index.php?search='+encodeURIComponent(doc[5])+'&title=Special:MediaSearch&type=image'}>Buscar reproducción en el archivo ↗</a></article></div>}<footer><span>LOS LIBROS BLANCOS</span><p>Una exposición digital sobre la Palestina bajo Mandato británico, 1922–1939.</p></footer></>}
function Accordion({items,open,setOpen}){return <div className="accordion">{items.map(([t,c],i)=>{let id=t+i;return <div className={open===id?'expanded':''}><button onClick={()=>setOpen(open===id?null:id)}><span>{t}</span><b>{open===id?'−':'+'}</b></button><p>{c}</p></div>})}</div>}
function Paper({id,year,title,official,accent,image,panels,quote,original,open,setOpen}){return <section id={id} className="section paper"><Reveal><div className="paper-heading"><div><p className="eyebrow">02 / Primera definición</p><span className="year">{year}</span><h2>{title}</h2><p className="official">{official}</p></div><img src={image} alt="Fotografía de Palestina bajo el Mandato"/></div></Reveal><div className="paper-layout"><div className="quote"><i>“{quote}”</i><details><summary>Ver original en inglés</summary><p>{original}</p></details></div><Accordion items={panels} open={open} setOpen={setOpen}/></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
